ANALYSIS_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "category",
        "department",
        "priority",
        "risk_level",
        "summary",
        "keywords",
        "evidence_checklist",
        "next_steps",
        "possible_legal_sections",
        "entities",
        "confidence",
        "reasoning",
        "language",
        "needs_human_review",
    ],
    "properties": {
        "category": {"type": "string"},
        "department": {"type": "string"},
        "priority": {"type": "string", "enum": ["High", "Medium", "Low"]},
        "risk_level": {"type": "string", "enum": ["Critical", "High", "Medium", "Low"]},
        "summary": {"type": "string"},
        "keywords": {"type": "array", "items": {"type": "string"}},
        "evidence_checklist": {"type": "array", "items": {"type": "string"}},
        "next_steps": {"type": "array", "items": {"type": "string"}},
        "possible_legal_sections": {"type": "array", "items": {"type": "string"}},
        "entities": {
            "type": "object",
            "additionalProperties": False,
            "required": [
                "amounts",
                "phone_numbers",
                "urls",
                "upi_ids",
                "emails",
                "dates",
                "times",
                "payment_methods",
                "counts",
                "vehicle_numbers",
                "social_handles",
                "platforms",
                "document_ids",
                "bank_references",
                "bank_accounts",
                "ip_addresses",
                "person_names",
                "locations",
            ],
            "properties": {
                "amounts": {"type": "array", "items": {"type": "string"}},
                "phone_numbers": {"type": "array", "items": {"type": "string"}},
                "urls": {"type": "array", "items": {"type": "string"}},
                "upi_ids": {"type": "array", "items": {"type": "string"}},
                "emails": {"type": "array", "items": {"type": "string"}},
                "dates": {"type": "array", "items": {"type": "string"}},
                "times": {"type": "array", "items": {"type": "string"}},
                "payment_methods": {"type": "array", "items": {"type": "string"}},
                "counts": {"type": "array", "items": {"type": "string"}},
                "vehicle_numbers": {"type": "array", "items": {"type": "string"}},
                "social_handles": {"type": "array", "items": {"type": "string"}},
                "platforms": {"type": "array", "items": {"type": "string"}},
                "document_ids": {"type": "array", "items": {"type": "string"}},
                "bank_references": {"type": "array", "items": {"type": "string"}},
                "bank_accounts": {"type": "array", "items": {"type": "string"}},
                "ip_addresses": {"type": "array", "items": {"type": "string"}},
                "person_names": {"type": "array", "items": {"type": "string"}},
                "locations": {"type": "array", "items": {"type": "string"}},
            },
        },
        "confidence": {"type": "number", "minimum": 0, "maximum": 1},
        "reasoning": {"type": "string"},
        "language": {"type": "string"},
        "needs_human_review": {"type": "boolean"},
    },
}


DEFAULT_ANALYSIS = {
    "category": "General Complaint",
    "department": "Police Control Room / Local Police Station",
    "priority": "Low",
    "risk_level": "Low",
    "summary": "",
    "keywords": [],
    "evidence_checklist": [
        "Complainant contact details",
        "Date and time of incident",
        "Any screenshots, documents, or messages related to the complaint",
    ],
    "next_steps": [
        "Review the complaint manually and route to the correct desk.",
        "Collect missing complainant identity and contact details.",
    ],
    "possible_legal_sections": [
        "Legal section suggestions require officer/legal review before FIR registration.",
    ],
    "entities": {
        "amounts": [],
        "phone_numbers": [],
        "urls": [],
        "upi_ids": [],
        "emails": [],
        "dates": [],
        "times": [],
        "payment_methods": [],
        "counts": [],
        "vehicle_numbers": [],
        "social_handles": [],
        "platforms": [],
        "document_ids": [],
        "bank_references": [],
        "bank_accounts": [],
        "ip_addresses": [],
        "person_names": [],
        "locations": [],
    },
    "confidence": 0.35,
    "reasoning": "Insufficient signal for a confident automated classification.",
    "language": "unknown",
    "needs_human_review": True,
}
